imagegen1:
  type: ImageGenServer
  model: /home/cc/tally-bench/ConsumerBench/models/stable-diffusion-3.5-medium-turbo
  num_requests: 20
  device: gpu
  api_port: 8021
  priority: 2
lv1:
  type: LiveCaptionsHF
  model: openai/whisper-large-v3-turbo
  num_requests: 1
  device: gpu
  api_port: 5011
  client_command_file: applications/LiveCaptions/whisper-earnings21/4320211_chunk_002.wav
  priority: 1
chat1:
  type: ChatbotHF
  model: meta-llama/Llama-3.2-3B-Instruct
  num_requests: 50
  device: gpu
  api_port: 8011
  priority: 2
workflows:
  generate_image:
    uses: imagegen1
  transcript:
    uses: lv1
  chat_summary:
    uses: chat1
scheduler: tally
