chat1:
    model: meta-llama/Llama-3.2-3B-Instruct
    num_requests: 20
    device: gpu
    type: Chatbot
    backend: vllm
    vllm_path: inference_backends/vllm
    api_port: 8080
    mps: 100

deep1:
    server_model: meta-llama/Llama-3.2-3B-Instruct
    client_model: openai/meta-llama/Llama-3.2-3B-Instruct
    num_requests: 1
    device: gpu
    type: DeepResearch
    backend: vllm
    vllm_path: inference_backends/vllm
    api_port: 8080
    mps: 100

workflows:
    chat_summary:
        uses: chat1

    deep_summary:
        uses: deep1
