scheduler: tally

chat1:
  type: ChatbotHF
  model: meta-llama/Llama-3.2-3B-Instruct
  device: gpu
  num_requests: 20
  api_port: 8011
  priority: 2

chat2:
  type: ChatbotHF
  model: meta-llama/Llama-3.2-3B-Instruct
  device: gpu
  num_requests: 20
  api_port: 8012
  priority: 1

workflows:
  chat_summary1:
    uses: chat1
  chat_summary2:
    uses: chat2