imagegen1:
    model: /home/tally-bench/ConsumerBench/models/stable-diffusion-3.5-medium-turbo
    # server_model: CompVis/stable-diffusion-v1-4
    num_requests: 10
    device: gpu
    type: ImageGen
    api_port: 8081
    # mps: 100

imagegen2:
    model: /home/tally-bench/ConsumerBench/models/stable-diffusion-3.5-medium-turbo
    # server_model: CompVis/stable-diffusion-v1-4
    num_requests: 10
    device: gpu
    type: ImageGenServer
    api_port: 8082
    # mps: 100

workflows:
    generate_image1:
        uses: imagegen1 
    
    generate_image2:
        uses: imagegen2