#scheduler: naive

lv:
    num_requests: 1
    device: gpu
    client_command_file: applications/LiveCaptions/whisper-earnings21/4320211_chunk_002.wav
    type: LiveCaptionsHF
    mps: 30

workflows:
    start_captions:
        uses: lv
