scheduler: naive

imagegen1:
    model: models/stable-diffusion-3.5-medium-turbo
    num_requests: 20
    device: gpu
    type: ImageGenServer
    api_port: 8082
    mps: 20

workflows:
    generate_image1:
        uses: imagegen1 
